# Generated by Django 2.0.4 on 2018-04-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата публикации')),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('category', models.SmallIntegerField(choices=[(0, 'Dessert'), (1, 'Meat')], null=True, verbose_name='Категории')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_list.User', verbose_name='Пользователь'),
        ),
    ]
