# Generated by Django 2.0.4 on 2018-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0002_auto_20180421_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
